apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: rodriggj/auth
      context: auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml